use super::opcode::Opcode;
use super::Cpu;

macro_rules! add_op {
    ($t:ident, $c:expr, $m:ident, $a:ident, $l:expr, $cy:expr, $ca:expr) => {
        add_op!(@expand $t, $c, $m, $a, $l, $cy, $ca, stringify!($m));
    };

    (@expand $t:ident, $c:expr, $m:ident, $a:ident, $l:expr, $cy:expr, $ca:expr, $mstr:expr) => {
        $t.push(Opcode{
            value: $c,
            mnemonic: $mstr,
            address_mode_fn: Cpu::$a,
            op_fn: Cpu::$m,
            len: $l,
            cycles: $cy,
            cycles_added: $ca,
            legal: match $mstr {
                "XXX" => false,
                _ => true,
            }
        })
    };
}

pub fn add_all_ops(table: &mut Vec<Opcode>) {
    add_op!(table, 0x00,  BRK,  Implied , 1, 7, 0);
    add_op!(table, 0x01,  BPL,  Relative, 2, 2, 1);
    add_op!(table, 0x02,  JSR,  Absolute, 3, 6, 0);
    add_op!(table, 0x03,  BMI,  Relative, 2, 2, 1);
    add_op!(table, 0x04,  RTI,  Implied , 1, 6, 0);
    add_op!(table, 0x05,  BVC,  Relative, 2, 2, 1);
    add_op!(table, 0x06,  RTS,  Implied , 1, 6, 0);
    add_op!(table, 0x07,  BVS,  Relative, 2, 2, 1);
    add_op!(table, 0x08,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x09,  BCC,  Relative, 2, 2, 1);
    add_op!(table, 0x0a,  LDY,  Imm     , 2, 2, 0);
    add_op!(table, 0x0b,  BCS,  Relative, 2, 2, 1);
    add_op!(table, 0x0c,  CPY,  Imm     , 2, 2, 0);
    add_op!(table, 0x0d,  BNE,  Relative, 2, 2, 1);
    add_op!(table, 0x0e,  CPX,  Imm     , 2, 2, 0);
    add_op!(table, 0x0f,  BEQ,  Relative, 2, 2, 1);
    add_op!(table, 0x10,  ORA,  IdxIndX , 2, 6, 0);
    add_op!(table, 0x11,  ORA,  IndIdxY , 2, 5, 2);
    add_op!(table, 0x12,  AND,  IdxIndX , 2, 6, 0);
    add_op!(table, 0x13,  AND,  IndIdxY , 2, 5, 2);
    add_op!(table, 0x14,  EOR,  IdxIndX , 2, 6, 0);
    add_op!(table, 0x15,  OR ,  IndIdxY , 2, 5, 2);
    add_op!(table, 0x16,  ADC,  IdxIndX , 2, 6, 0);
    add_op!(table, 0x17,  ADC,  IndIdxY , 2, 5, 2);
    add_op!(table, 0x18,  STA,  IdxIndX , 2, 6, 0);
    add_op!(table, 0x19,  STA,  IndIdxY , 2, 6, 0);
    add_op!(table, 0x1a,  LDA,  IdxIndX , 2, 6, 0);
    add_op!(table, 0x1b,  LDA,  IndIdxY , 2, 5, 2);
    add_op!(table, 0x1c,  CMP,  IdxIndX , 2, 6, 0);
    add_op!(table, 0x1d,  CMP,  IndIdxY , 2, 5, 2);
    add_op!(table, 0x1e,  SBC,  IdxIndX , 2, 6, 0);
    add_op!(table, 0x1f,  SBC,  IndIdxY , 2, 5, 2);
    add_op!(table, 0x20,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x21,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x22,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x23,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x24,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x25,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x26,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x27,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x28,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x29,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x2a,  LDX,  Imm     , 2, 2, 0);
    add_op!(table, 0x2b,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x2c,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x2d,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x2e,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x2f,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x30,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x31,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x32,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x33,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x34,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x35,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x36,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x37,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x38,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x39,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x3a,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x3b,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x3c,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x3d,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x3e,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x3f,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x40,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x41,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x42,  BIT,  ZP      , 2, 3, 0);
    add_op!(table, 0x43,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x44,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x45,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x46,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x47,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x48,  STY,  ZP      , 2, 3, 0);
    add_op!(table, 0x49,  STY,  IdxZPX  , 2, 4, 0);
    add_op!(table, 0x4a,  LDY,  ZP      , 2, 3, 0);
    add_op!(table, 0x4b,  LDY,  IdxZPX  , 2, 4, 0);
    add_op!(table, 0x4c,  CPY,  ZP      , 2, 3, 0);
    add_op!(table, 0x4d,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x4e,  CPX,  ZP      , 2, 3, 0);
    add_op!(table, 0x4f,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x50,  ORA,  ZP      , 2, 3, 0);
    add_op!(table, 0x51,  ORA,  IdxZPX  , 2, 4, 0);
    add_op!(table, 0x52,  AND,  ZP      , 2, 3, 0);
    add_op!(table, 0x53,  AND,  IdxZPX  , 2, 4, 0);
    add_op!(table, 0x54,  EOR,  ZP      , 2, 3, 0);
    add_op!(table, 0x55,  EOR,  IdxZPX  , 2, 4, 0);
    add_op!(table, 0x56,  ADC,  ZP      , 2, 3, 0);
    add_op!(table, 0x57,  ADC,  IdxZPX  , 2, 4, 0);
    add_op!(table, 0x58,  STA,  ZP      , 2, 3, 0);
    add_op!(table, 0x59,  STA,  IdxZPX  , 2, 4, 0);
    add_op!(table, 0x5a,  LDA,  ZP      , 2, 3, 0);
    add_op!(table, 0x5b,  LDA,  IdxZPX  , 2, 4, 0);
    add_op!(table, 0x5c,  CMP,  ZP      , 2, 3, 0);
    add_op!(table, 0x5d,  CMP,  IdxZPX  , 2, 4, 0);
    add_op!(table, 0x5e,  SBC,  ZP      , 2, 3, 0);
    add_op!(table, 0x5f,  SBC,  IdxZPX  , 2, 4, 0);
    add_op!(table, 0x60,  ASL,  ZP      , 2, 5, 0);
    add_op!(table, 0x61,  ASL,  IdxZPX  , 2, 6, 0);
    add_op!(table, 0x62,  ROL,  ZP      , 2, 5, 0);
    add_op!(table, 0x63,  ROL,  IdxZPX  , 2, 6, 0);
    add_op!(table, 0x64,  LSR,  ZP      , 2, 5, 0);
    add_op!(table, 0x65,  LSR,  IdxZPX  , 2, 6, 0);
    add_op!(table, 0x66,  ROR,  ZP      , 2, 5, 0);
    add_op!(table, 0x67,  ROR,  IdxZPX  , 2, 6, 0);
    add_op!(table, 0x68,  STX,  ZP      , 2, 3, 0);
    add_op!(table, 0x69,  STX,  IdxZPY  , 2, 4, 0);
    add_op!(table, 0x6a,  LDX,  ZP      , 2, 3, 0);
    add_op!(table, 0x6b,  LDX,  IdxZPY  , 2, 4, 0);
    add_op!(table, 0x6c,  DEC,  ZP      , 2, 5, 0);
    add_op!(table, 0x6d,  DEC,  IdxZPX  , 2, 6, 0);
    add_op!(table, 0x6e,  INC,  ZP      , 2, 5, 0);
    add_op!(table, 0x6f,  INC,  IdxZPX  , 2, 6, 0);
    add_op!(table, 0x70,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x71,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x72,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x73,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x74,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x75,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x76,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x77,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x78,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x79,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x7a,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x7b,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x7c,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x7d,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x7e,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x7f,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x80,  PHP,  Implied , 1, 3, 0);
    add_op!(table, 0x81,  CLC,  Implied , 1, 2, 0);
    add_op!(table, 0x82,  PLP,  Implied , 1, 4, 0);
    add_op!(table, 0x83,  SEC,  Implied , 1, 2, 0);
    add_op!(table, 0x84,  PHA,  Implied , 1, 3, 0);
    add_op!(table, 0x85,  CLI,  Implied , 1, 2, 0);
    add_op!(table, 0x86,  PLA,  Implied , 1, 4, 0);
    add_op!(table, 0x87,  SEI,  Implied , 1, 2, 0);
    add_op!(table, 0x88,  DEY,  Implied , 1, 2, 0);
    add_op!(table, 0x89,  TYA,  Implied , 1, 2, 0);
    add_op!(table, 0x8a,  TAY,  Implied , 1, 2, 0);
    add_op!(table, 0x8b,  CLV,  Implied , 1, 2, 0);
    add_op!(table, 0x8c,  INY,  Implied , 1, 2, 0);
    add_op!(table, 0x8d,  CLD,  Implied , 1, 2, 0);
    add_op!(table, 0x8e,  INX,  Implied , 1, 2, 0);
    add_op!(table, 0x8f,  SED,  Implied , 1, 2, 0);
    add_op!(table, 0x90,  ORA,  Imm     , 2, 2, 0);
    add_op!(table, 0x91,  ORA,  IdxAbsY , 3, 4, 2);
    add_op!(table, 0x92,  AND,  Imm     , 2, 2, 0);
    add_op!(table, 0x93,  AND,  IdxAbsY , 3, 4, 2);
    add_op!(table, 0x94,  EOR,  Imm     , 2, 2, 0);
    add_op!(table, 0x95,  EOR,  IdxAbsY , 3, 4, 2);
    add_op!(table, 0x96,  ADC,  Imm     , 2, 2, 0);
    add_op!(table, 0x97,  ADC,  IdxAbsY , 3, 4, 2);
    add_op!(table, 0x98,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0x99,  STA,  IdxAbsY , 3, 5, 0);
    add_op!(table, 0x9a,  LDA,  Imm     , 2, 2, 0);
    add_op!(table, 0x9b,  LDA,  IdxAbsY , 3, 4, 2);
    add_op!(table, 0x9c,  CMP,  Imm     , 2, 2, 0);
    add_op!(table, 0x9d,  CMP,  IdxAbsY , 3, 4, 2);
    add_op!(table, 0x9e,  SBC,  Imm     , 2, 2, 0);
    add_op!(table, 0x9f,  SBC,  IdxAbsY , 3, 4, 2);
    add_op!(table, 0xa0,  ASL,  Accum   , 1, 2, 0);
    add_op!(table, 0xa1,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xa2,  ROL,  Accum   , 1, 2, 0);
    add_op!(table, 0xa3,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xa4,  LSR,  Accum   , 1, 2, 0);
    add_op!(table, 0xa5,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xa6,  ROR,  Accum   , 1, 2, 0);
    add_op!(table, 0xa7,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xa8,  TXA,  Implied , 1, 2, 0);
    add_op!(table, 0xa9,  TXS,  Implied , 1, 2, 0);
    add_op!(table, 0xaa,  TAX,  Implied , 1, 2, 0);
    add_op!(table, 0xab,  TSX,  Implied , 1, 2, 0);
    add_op!(table, 0xac,  DEX,  Implied , 1, 2, 0);
    add_op!(table, 0xad,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xae,  NP ,  Implied , 1, 2, 0);
    add_op!(table, 0xaf,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xb0,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xb1,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xb2,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xb3,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xb4,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xb5,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xb6,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xb7,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xb8,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xb9,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xba,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xbb,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xbc,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xbd,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xbe,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xbf,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xc0,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xc1,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xc2,  BIT,  Absolute, 3, 4, 0);
    add_op!(table, 0xc3,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xc4,  JMP,  Absolute, 3, 3, 0);
    add_op!(table, 0xc5,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xc6,  JMP,  Indirect, 3, 5, 0);
    add_op!(table, 0xc7,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xc8,  STY,  Absolute, 3, 4, 0);
    add_op!(table, 0xc9,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xca,  LDY,  Absolute, 3, 4, 0);
    add_op!(table, 0xcb,  LDY,  IdxAbsX , 3, 4, 1);
    add_op!(table, 0xcc,  CPY,  Absolute, 3, 4, 0);
    add_op!(table, 0xcd,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xce,  CPX,  Absolute, 3, 4, 0);
    add_op!(table, 0xcf,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xd0,  ORA,  Absolute, 3, 4, 0);
    add_op!(table, 0xd1,  ORA,  IdxAbsX , 3, 4, 2);
    add_op!(table, 0xd2,  AND,  Absolute, 3, 4, 0);
    add_op!(table, 0xd3,  AND,  IdxAbsX , 3, 4, 2);
    add_op!(table, 0xd4,  EOR,  Absolute, 3, 4, 0);
    add_op!(table, 0xd5,  EOR,  IdxAbsX , 3, 4, 2);
    add_op!(table, 0xd6,  ADC,  Absolute, 3, 4, 0);
    add_op!(table, 0xd7,  ADC,  IdxAbsX , 3, 4, 2);
    add_op!(table, 0xd8,  STA,  Absolute, 3, 4, 0);
    add_op!(table, 0xd9,  STA,  IdxAbsX , 3, 5, 0);
    add_op!(table, 0xda,  LDA,  Absolute, 3, 4, 0);
    add_op!(table, 0xdb,  LDA,  IdxAbsX , 3, 4, 2);
    add_op!(table, 0xdc,  CMP,  Absolute, 3, 4, 0);
    add_op!(table, 0xdd,  CMP,  IdxAbsX , 3, 4, 0);
    add_op!(table, 0xde,  SBC,  Absolute, 3, 4, 0);
    add_op!(table, 0xdf,  SBC,  IdxAbsX , 3, 4, 2);
    add_op!(table, 0xe0,  ASL,  Absolute, 3, 6, 0);
    add_op!(table, 0xe1,  ASL,  IdxAbsX , 3, 7, 0);
    add_op!(table, 0xe2,  ROL,  Absolute, 3, 6, 0);
    add_op!(table, 0xe3,  ROL,  IdxAbsX , 3, 7, 0);
    add_op!(table, 0xe4,  LSR,  Absolute, 3, 6, 0);
    add_op!(table, 0xe5,  LSR,  IdxAbsX , 3, 7, 0);
    add_op!(table, 0xe6,  ROR,  Absolute, 3, 6, 0);
    add_op!(table, 0xe7,  ROR,  IdxAbsX , 3, 7, 0);
    add_op!(table, 0xe8,  STX,  Absolute, 3, 4, 0);
    add_op!(table, 0xe9,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xea,  LDX,  Absolute, 3, 4, 0);
    add_op!(table, 0xeb,  LDX,  IdxAbsY , 3, 4, 2);
    add_op!(table, 0xec,  DEC,  Absolute, 3, 6, 0);
    add_op!(table, 0xed,  DEC,  IdxAbsX , 3, 7, 0);
    add_op!(table, 0xee,  INC,  Absolute, 3, 6, 0);
    add_op!(table, 0xef,  INC,  IdxAbsX , 3, 7, 0);
    add_op!(table, 0xf0,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xf1,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xf2,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xf3,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xf4,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xf5,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xf6,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xf7,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xf8,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xf9,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xfa,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xfb,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xfc,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xfd,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xfe,  XXX,  Implied , 1, 2, 0);
    add_op!(table, 0xff,  XXX,  Implied , 1, 2, 0);
}
