use crate::{Mnemonic, AddrMode};

use super::Operation;

macro_rules! op {
    ($opcode:expr, $mnemonic:expr, $addr:expr, $size:expr, $cyc:expr, $extra:expr) => {
        Operation {
            opcode: $opcode,
            mnemonic: $mnemonic,
            addr_mode: $addr,
            size: $size,
            cycles: $cyc,
            extra_cycles: $extra,
        }
    };
}

#[allow(dead_code)]
pub const OPTABLE: [Operation; 256] = [
    op!(0x00, Mnemonic::BRK, AddrMode::Implied , 1, 7, 0),
    op!(0x01, Mnemonic::ORA, AddrMode::IdxIndX , 2, 6, 0),
    op!(0x02, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x03, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x04, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x05, Mnemonic::ORA, AddrMode::ZP      , 2, 3, 0),
    op!(0x06, Mnemonic::ASL, AddrMode::ZP      , 2, 5, 0),
    op!(0x07, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x08, Mnemonic::PHP, AddrMode::Implied , 1, 3, 0),
    op!(0x09, Mnemonic::ORA, AddrMode::Imm     , 2, 2, 0),
    op!(0x0a, Mnemonic::ASL, AddrMode::Accum   , 1, 2, 0),
    op!(0x0b, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x0c, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x0d, Mnemonic::ORA, AddrMode::Absolute, 3, 4, 0),
    op!(0x0e, Mnemonic::ASL, AddrMode::Absolute, 3, 6, 0),
    op!(0x0f, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x10, Mnemonic::BPL, AddrMode::Relative, 2, 2, 2),
    op!(0x11, Mnemonic::ORA, AddrMode::IndIdxY , 2, 5, 1),
    op!(0x12, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x13, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x14, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x15, Mnemonic::ORA, AddrMode::IdxZPX  , 2, 4, 0),
    op!(0x16, Mnemonic::ASL, AddrMode::IdxZPX  , 2, 6, 0),
    op!(0x17, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x18, Mnemonic::CLC, AddrMode::Implied , 1, 2, 0),
    op!(0x19, Mnemonic::ORA, AddrMode::IdxAbsY , 3, 4, 1),
    op!(0x1a, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x1b, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x1c, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x1d, Mnemonic::ORA, AddrMode::IdxAbsX , 3, 4, 1),
    op!(0x1e, Mnemonic::ASL, AddrMode::IdxAbsX , 3, 7, 0),
    op!(0x1f, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x20, Mnemonic::JSR, AddrMode::Absolute, 3, 6, 0),
    op!(0x21, Mnemonic::AND, AddrMode::IdxIndX , 2, 6, 0),
    op!(0x22, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x23, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x24, Mnemonic::BIT, AddrMode::ZP      , 2, 3, 0),
    op!(0x25, Mnemonic::AND, AddrMode::ZP      , 2, 3, 0),
    op!(0x26, Mnemonic::ROL, AddrMode::ZP      , 2, 5, 0),
    op!(0x27, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x28, Mnemonic::PLP, AddrMode::Implied , 1, 4, 0),
    op!(0x29, Mnemonic::AND, AddrMode::Imm     , 2, 2, 0),
    op!(0x2a, Mnemonic::ROL, AddrMode::Accum   , 1, 2, 0),
    op!(0x2b, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x2c, Mnemonic::BIT, AddrMode::Absolute, 3, 4, 0),
    op!(0x2d, Mnemonic::AND, AddrMode::Absolute, 3, 4, 0),
    op!(0x2e, Mnemonic::ROL, AddrMode::Absolute, 3, 6, 0),
    op!(0x2f, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x30, Mnemonic::BMI, AddrMode::Relative, 2, 2, 2),
    op!(0x31, Mnemonic::AND, AddrMode::IndIdxY , 2, 5, 1),
    op!(0x32, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x33, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x34, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x35, Mnemonic::AND, AddrMode::IdxZPX  , 2, 4, 0),
    op!(0x36, Mnemonic::ROL, AddrMode::IdxZPX  , 2, 6, 0),
    op!(0x37, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x38, Mnemonic::SEC, AddrMode::Implied , 1, 2, 0),
    op!(0x39, Mnemonic::AND, AddrMode::IdxAbsY , 3, 4, 1),
    op!(0x3a, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x3b, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x3c, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x3d, Mnemonic::AND, AddrMode::IdxAbsX , 3, 4, 1),
    op!(0x3e, Mnemonic::ROL, AddrMode::IdxAbsX , 3, 7, 0),
    op!(0x3f, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x40, Mnemonic::RTI, AddrMode::Implied , 1, 6, 0),
    op!(0x41, Mnemonic::EOR, AddrMode::IdxIndX , 2, 6, 0),
    op!(0x42, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x43, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x44, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x45, Mnemonic::EOR, AddrMode::ZP      , 2, 3, 0),
    op!(0x46, Mnemonic::LSR, AddrMode::ZP      , 2, 5, 0),
    op!(0x47, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x48, Mnemonic::PHA, AddrMode::Implied , 1, 3, 0),
    op!(0x49, Mnemonic::EOR, AddrMode::Imm     , 2, 2, 0),
    op!(0x4a, Mnemonic::LSR, AddrMode::Accum   , 1, 2, 0),
    op!(0x4b, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x4c, Mnemonic::JMP, AddrMode::Absolute, 3, 3, 0),
    op!(0x4d, Mnemonic::EOR, AddrMode::Absolute, 3, 4, 0),
    op!(0x4e, Mnemonic::LSR, AddrMode::Absolute, 3, 6, 0),
    op!(0x4f, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x50, Mnemonic::BVC, AddrMode::Relative, 2, 2, 2),
    op!(0x51, Mnemonic::EOR ,AddrMode:: IndIdxY, 2, 5, 1),
    op!(0x52, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x53, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x54, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x55, Mnemonic::EOR, AddrMode::IdxZPX  , 2, 4, 0),
    op!(0x56, Mnemonic::LSR, AddrMode::IdxZPX  , 2, 6, 0),
    op!(0x57, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x58, Mnemonic::CLI, AddrMode::Implied , 1, 2, 0),
    op!(0x59, Mnemonic::EOR, AddrMode::IdxAbsY , 3, 4, 1),
    op!(0x5a, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x5b, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x5c, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x5d, Mnemonic::EOR, AddrMode::IdxAbsX , 3, 4, 1),
    op!(0x5e, Mnemonic::LSR, AddrMode::IdxAbsX , 3, 7, 0),
    op!(0x5f, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x60, Mnemonic::RTS, AddrMode::Implied , 1, 6, 0),
    op!(0x61, Mnemonic::ADC, AddrMode::IdxIndX , 2, 6, 0),
    op!(0x62, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x63, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x64, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x65, Mnemonic::ADC, AddrMode::ZP      , 2, 3, 0),
    op!(0x66, Mnemonic::ROR, AddrMode::ZP      , 2, 5, 0),
    op!(0x67, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x68, Mnemonic::PLA, AddrMode::Implied , 1, 4, 0),
    op!(0x69, Mnemonic::ADC, AddrMode::Imm     , 2, 2, 0),
    op!(0x6a, Mnemonic::ROR, AddrMode::Accum   , 1, 2, 0),
    op!(0x6b, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x6c, Mnemonic::JMP, AddrMode::Indirect, 3, 5, 0),
    op!(0x6d, Mnemonic::ADC, AddrMode::Absolute, 3, 4, 0),
    op!(0x6e, Mnemonic::ROR, AddrMode::Absolute, 3, 6, 0),
    op!(0x6f, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x70, Mnemonic::BVS, AddrMode::Relative, 2, 2, 2),
    op!(0x71, Mnemonic::ADC, AddrMode::IndIdxY , 2, 5, 1),
    op!(0x72, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x73, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x74, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x75, Mnemonic::ADC, AddrMode::IdxZPX  , 2, 4, 0),
    op!(0x76, Mnemonic::ROR, AddrMode::IdxZPX  , 2, 6, 0),
    op!(0x77, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x78, Mnemonic::SEI, AddrMode::Implied , 1, 2, 0),
    op!(0x79, Mnemonic::ADC, AddrMode::IdxAbsY , 3, 4, 1),
    op!(0x7a, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x7b, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x7c, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x7d, Mnemonic::ADC, AddrMode::IdxAbsX , 3, 4, 1),
    op!(0x7e, Mnemonic::ROR, AddrMode::IdxAbsX , 3, 7, 0),
    op!(0x7f, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x80, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x81, Mnemonic::STA, AddrMode::IdxIndX , 2, 6, 0),
    op!(0x82, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x83, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x84, Mnemonic::STY, AddrMode::ZP      , 2, 3, 0),
    op!(0x85, Mnemonic::STA, AddrMode::ZP      , 2, 3, 0),
    op!(0x86, Mnemonic::STX, AddrMode::ZP      , 2, 3, 0),
    op!(0x87, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x88, Mnemonic::DEY, AddrMode::Implied , 1, 2, 0),
    op!(0x89, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x8a, Mnemonic::TXA, AddrMode::Implied , 1, 2, 0),
    op!(0x8b, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x8c, Mnemonic::STY, AddrMode::Absolute, 3, 4, 0),
    op!(0x8d, Mnemonic::STA, AddrMode::Absolute, 3, 4, 0),
    op!(0x8e, Mnemonic::STX, AddrMode::Absolute, 3, 4, 0),
    op!(0x8f, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x90, Mnemonic::BCC, AddrMode::Relative, 2, 2, 2),
    op!(0x91, Mnemonic::STA, AddrMode::IndIdxY , 2, 6, 0),
    op!(0x92, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x93, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x94, Mnemonic::STY, AddrMode::IdxZPX  , 2, 4, 0),
    op!(0x95, Mnemonic::STA, AddrMode::IdxZPX  , 2, 4, 0),
    op!(0x96, Mnemonic::STX, AddrMode::IdxZPY  , 2, 4, 0),
    op!(0x97, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x98, Mnemonic::TYA, AddrMode::Implied , 1, 2, 0),
    op!(0x99, Mnemonic::STA, AddrMode::IdxAbsY , 3, 5, 0),
    op!(0x9a, Mnemonic::TXS, AddrMode::Implied , 1, 2, 0),
    op!(0x9b, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x9c, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x9d, Mnemonic::STA, AddrMode::IdxAbsX , 3, 5, 0),
    op!(0x9e, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0x9f, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xa0, Mnemonic::LDY, AddrMode::Imm     , 2, 2, 0),
    op!(0xa1, Mnemonic::LDA, AddrMode::IdxIndX , 2, 6, 0),
    op!(0xa2, Mnemonic::LDX, AddrMode::Imm     , 2, 2, 0),
    op!(0xa3, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xa4, Mnemonic::LDY, AddrMode::ZP      , 2, 3, 0),
    op!(0xa5, Mnemonic::LDA, AddrMode::ZP      , 2, 3, 0),
    op!(0xa6, Mnemonic::LDX, AddrMode::ZP      , 2, 3, 0),
    op!(0xa7, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xa8, Mnemonic::TAY, AddrMode::Implied , 1, 2, 0),
    op!(0xa9, Mnemonic::LDA, AddrMode::Imm     , 2, 2, 0),
    op!(0xaa, Mnemonic::TAX, AddrMode::Implied , 1, 2, 0),
    op!(0xab, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xac, Mnemonic::LDY, AddrMode::Absolute, 3, 4, 0),
    op!(0xad, Mnemonic::LDA, AddrMode::Absolute, 3, 4, 0),
    op!(0xae, Mnemonic::LDX, AddrMode::Absolute, 3, 4, 0),
    op!(0xaf, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xb0, Mnemonic::BCS, AddrMode::Relative, 2, 2, 2),
    op!(0xb1, Mnemonic::LDA, AddrMode::IndIdxY , 2, 5, 1),
    op!(0xb2, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xb3, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xb4, Mnemonic::LDY, AddrMode::IdxZPX  , 2, 4, 0),
    op!(0xb5, Mnemonic::LDA, AddrMode::IdxZPX  , 2, 4, 0),
    op!(0xb6, Mnemonic::LDX, AddrMode::IdxZPY  , 2, 4, 0),
    op!(0xb7, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xb8, Mnemonic::CLV, AddrMode::Implied , 1, 2, 0),
    op!(0xb9, Mnemonic::LDA, AddrMode::IdxAbsY , 3, 4, 1),
    op!(0xba, Mnemonic::TSX, AddrMode::Implied , 1, 2, 0),
    op!(0xbb, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xbc, Mnemonic::LDY, AddrMode::IdxAbsX , 3, 4, 1),
    op!(0xbd, Mnemonic::LDA, AddrMode::IdxAbsX , 3, 4, 1),
    op!(0xbe, Mnemonic::LDX, AddrMode::IdxAbsY , 3, 4, 1),
    op!(0xbf, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xc0, Mnemonic::CPY, AddrMode::Imm     , 2, 2, 0),
    op!(0xc1, Mnemonic::CMP, AddrMode::IdxIndX , 2, 6, 0),
    op!(0xc2, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xc3, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xc4, Mnemonic::CPY, AddrMode::ZP      , 2, 3, 0),
    op!(0xc5, Mnemonic::CMP, AddrMode::ZP      , 2, 3, 0),
    op!(0xc6, Mnemonic::DEC, AddrMode::ZP      , 2, 5, 0),
    op!(0xc7, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xc8, Mnemonic::INY, AddrMode::Implied , 1, 2, 0),
    op!(0xc9, Mnemonic::CMP, AddrMode::Imm     , 2, 2, 0),
    op!(0xca, Mnemonic::DEX, AddrMode::Implied , 1, 2, 0),
    op!(0xcb, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xcc, Mnemonic::CPY, AddrMode::Absolute, 3, 4, 0),
    op!(0xcd, Mnemonic::CMP, AddrMode::Absolute, 3, 4, 0),
    op!(0xce, Mnemonic::DEC, AddrMode::Absolute, 3, 6, 0),
    op!(0xcf, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xd0, Mnemonic::BNE, AddrMode::Relative, 2, 2, 2),
    op!(0xd1, Mnemonic::CMP, AddrMode::IndIdxY , 2, 5, 1),
    op!(0xd2, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xd3, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xd4, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xd5, Mnemonic::CMP, AddrMode::IdxZPX  , 2, 4, 0),
    op!(0xd6, Mnemonic::DEC, AddrMode::IdxZPX  , 2, 6, 0),
    op!(0xd7, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xd8, Mnemonic::CLD, AddrMode::Implied , 1, 2, 0),
    op!(0xd9, Mnemonic::CMP, AddrMode::IdxAbsY , 3, 4, 1),
    op!(0xda, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xdb, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xdc, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xdd, Mnemonic::CMP, AddrMode::IdxAbsX , 3, 4, 0),
    op!(0xde, Mnemonic::DEC, AddrMode::IdxAbsX , 3, 7, 0),
    op!(0xdf, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xe0, Mnemonic::CPX, AddrMode::Imm     , 2, 2, 0),
    op!(0xe1, Mnemonic::SBC, AddrMode::IdxIndX , 2, 6, 0),
    op!(0xe2, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xe3, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xe4, Mnemonic::CPX, AddrMode::ZP      , 2, 3, 0),
    op!(0xe5, Mnemonic::SBC, AddrMode::ZP      , 2, 3, 0),
    op!(0xe6, Mnemonic::INC, AddrMode::ZP      , 2, 5, 0),
    op!(0xe7, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xe8, Mnemonic::INX, AddrMode::Implied , 1, 2, 0),
    op!(0xe9, Mnemonic::SBC, AddrMode::Imm     , 2, 2, 0),
    op!(0xea, Mnemonic::NOP, AddrMode:: Implied, 1, 2, 0),
    op!(0xeb, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xec, Mnemonic::CPX, AddrMode::Absolute, 3, 4, 0),
    op!(0xed, Mnemonic::SBC, AddrMode::Absolute, 3, 4, 0),
    op!(0xee, Mnemonic::INC, AddrMode::Absolute, 3, 6, 0),
    op!(0xef, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xf0, Mnemonic::BEQ, AddrMode::Relative, 2, 2, 2),
    op!(0xf1, Mnemonic::SBC, AddrMode::IndIdxY , 2, 5, 1),
    op!(0xf2, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xf3, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xf4, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xf5, Mnemonic::SBC, AddrMode::IdxZPX  , 2, 4, 0),
    op!(0xf6, Mnemonic::INC, AddrMode::IdxZPX  , 2, 6, 0),
    op!(0xf7, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xf8, Mnemonic::SED, AddrMode::Implied , 1, 2, 0),
    op!(0xf9, Mnemonic::SBC, AddrMode::IdxAbsY , 3, 4, 1),
    op!(0xfa, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xfb, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xfc, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
    op!(0xfd, Mnemonic::SBC, AddrMode::IdxAbsX , 3, 4, 1),
    op!(0xfe, Mnemonic::INC, AddrMode::IdxAbsX , 3, 7, 0),
    op!(0xff, Mnemonic::XXX, AddrMode::Implied , 1, 2, 0),
];